### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by Fcornetg** [hijonathan/google-scripts#12]
Hello Jonathan,
I'm trying to use your code to backup an url  and i'm not being able of getting the full html of the web. I think is some kind of problem related to the web asking to have javascript enabled since in the middle of all the mess that is written in the file, you can read: " You need to enable JavaScript to run this app." 
Do you know any solution to this issue?
thanks!
Fernando

**Comment by hijonathan** [comment]
Hey @Fcornetg, cool that you're using this.

The problem you're probably running into is that this script only downloads the HTML, not the Javascript or CSS associated with that page. That's why you get that error when trying to open the HTML file locally.

You might want to try something like https://websitedownloader.io/ instead.

Good luck!
